name: 'Cache eslint'
description: 'Restore and cache eslint cache'
runs:
  using: 'composite'
  steps:
    - name: Cache eslint
      uses: actions/cache@v4
      env:
        cache-name: cache-eslint-v1
      with:
        path: |
          ${{ github.workspace }}/.eslintcache
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/*.ts', '**/*.tsx') }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
