name: Build Docker Image

inputs:
  image_tag:
    description: 'Docker image tag'
    required: true

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          darabus/homelab-rabus:${{ inputs.image_tag }}
        build-args: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          API_KEY=${{ secrets.API_KEY }}
          PEPPER=${{ secrets.PEPPER }}
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
