name: Deploy on Raspberry Pi
on:
  schedule:
    - cron: '0 4 * * *'

env:
  CHECKOUT_REF: ${{ github.event.pull_request.head.ref || github.ref_name }}
  SSH_HELLO_RABUS_PRIVATE: ${{ secrets.SSH_HELLO_RABUS_PRIVATE }}
  RASPI_HOST: ${{ secrets.RASPI_HOST }}
  RASPI_USER: ${{ secrets.RASPI_USER }}
  PEPPER: ${{ secrets.PEPPER }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    name: 'Login to Raspberry Pi & Redeploy'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: production
    steps:
      - name: Deploy on Remote Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.RASPI_HOST }}
          username: ${{ env.RASPI_USER }}
          key: ${{ env.SSH_HELLO_RABUS_PRIVATE }}
          script: |
            set -e  # Stop execution if any command fails

            echo "🚀 Starting Deployment on Raspberry Pi"

            # Navigate to the project directory
            cd ~/projects/homelab-rabus || exit 1
            echo "📂 Moved to project directory"

            # Login to Docker
            echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

            # Fetch latest changes from GitHub
            echo "🔄 Pulling latest changes from Git..."
            git checkout main || exit 1

            # Pull the latest changes from the main branch
            git pull origin main || exit 1
            echo "✅ Latest changes pulled successfully"

            # Create/update .env file safely
            echo "🔑 Updating .env file..."
            cat <<EOF > .env.production
            PEPPER=${{ env.PEPPER }}
            SESSION_SECRET=${{ env.SESSION_SECRET }}
            DATABASE_URL=${{ env.DATABASE_URL }}
            BLOB_READ_WRITE_TOKEN=${{ env.BLOB_READ_WRITE_TOKEN }}
            EOF

            echo "✅ .env file updated successfully"

            echo "🐳 Pulling latest image..."
            docker compose pull next-app
            echo "🚀 Restarting containers..."
            docker compose up -d --build --force-recreate

            echo "🎉 Deployment completed successfully!"
