name: Lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CHECKOUT_REF: ${{ github.event.pull_request.head.ref || github.ref_name }}

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
          ref: ${{ env.CHECKOUT_REF }}

      - name: Init CI Job
        uses: ./.github/actions/init-ci-job

      - name: Cache eslint
        uses: ./.github/actions/cache-eslint

      - name: Lint
        run: npm run lint

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'
